### ISSUE TITLE
Transfering funds more than available balance should return an error.

### ISSUE THREAD

**Issue by olivierb2** [Aventus-Network-Services/avn-api#4]
Today, API accept a transfer even if this one is higher than the user balance. It's better to get an error this is can be handling correctly from our wallet.

**Comment by nahuseyoum** [comment]
The API will accept all correctly structured transactions and acknowledges with a response that contains a `requestId`. 

The acknowledgement does not mean the transaction is executed successfully on chain, it only means the API has accepted the request to send the given transaction. To find the execution outcome, users must poll using the `requestId` sent back by the API.

If the transaction fails to be executed on chain (due to insufficient balance for example), the API will respond with a `Rejected` status when polled for the outcome of the transaction.
